# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7555fcaea25370b139dd60c3b471c7ac"
name = "whats-more"
handle = "whats-more-1"
application_url = "https://historic-submission-correction-operational.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://historic-submission-correction-operational.trycloudflare.com/auth/callback",
  "https://historic-submission-correction-operational.trycloudflare.com/auth/shopify/callback",
  "https://historic-submission-correction-operational.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
